### PR TITLE
Release 0.10.0: migration to rio-tiler

### PR DESCRIPTION
**Pull request by banesullivan**
This is a rather massive reimplementation of localtileserver that transitions to using [rio-tiler](https://github.com/cogeotiff/rio-tiler) entirely for all tiling needs and drops all usage of large-image.

Been working on this for a long time...

This release unfortunately has many breaking changes and some loss of features. The breaking changes are mostly around API renaming and some methods changing to properties. Otherwise, I stripped out features that are just better handled upstream or not needed here.

cc @giswqs, this may be a painful upgrade considering how much has changed. Highlights:

- `band` is now `indexes` to follow rio-tiler's implementation
- `cmap` is now `colormap`
- `palette` is now `colormap`
- Custom colormaps are no longer supported
- No more region of interest extraction
- ...

### CODE REVIEW

**Comment by banesullivan** [comment]
@giswqs, I'm going to merge this and issue pre-releases for testing. Do you have the bandwidth to validate this new version against leafmap?

**Comment by banesullivan** [comment]
Installation can be done with the `--pre` option for pip:

```
pip install --pre --no-cache localtileserver
```

**Comment by giswqs** [comment]
@banesullivan Excellent work! Thank you very much for your work on this. I will test it and update leafmap accordingly later this week. The new semester starts tomorrow, and I won't be able to follow up on this until later this week.

**Comment by banesullivan** [comment]
No worries! I'm only issue a pre-release and want to make sure that downstream packages like leafmap are still going to be well supported here. No rush but when you get around to it, don't hesitate to report what's broken

**Pull request merged**
