### PR TITLE
Support for custom colormaps

### LINKED ISSUE #200: Support custom colormaps
Originally reported in https://github.com/opengeos/leafmap/discussions/673#discussioncomment-8405398

This was supported in previous versions of localtileserver but was removed in the recent transition to rio-tiler

Here's psuedocode for what usage might look like:

```py
cmap1 = ListedColormap(['red','blue'],name='test_1')
cmap2 = ListedColormap(['blue','green'],name='test_2')
cmap3 = ListedColormap(['green','red'],name='test_3')

layer1 = get_leaflet_tile_layer(client, indexes=[2,1,3], cmap=[cmap2,cmap1,cmap3])

layer2 = get_leaflet_tile_layer(client, indexes=[2], cmap=cmap2)
```

### PR DESCRIPTION
**Pull request by lopezvoliver**
This pull request adds support for custom colormaps (resolves #200), either as a matplotlib Colormap, or as a list of colors. 

Hopefully I got it right, so far my tests (with `leafmap.add_raster`) seem to work:

Test using leafmap add_raster

Here's a test using the example from https://github.com/opengeos/leafmap/discussions/673

Test using leafmap add_raster

### CODE REVIEW

**Comment by giswqs** [comment]
This would be a nice addition. Great work!

**Comment by banesullivan** [comment]
Fantastic! I'll give this a test tonight and see if I can write a few tests. Thank you so much for contributing this!

**Comment by banesullivan** [comment]
This isn't quite working as expected for colormaps. I'm eager to incorporate this but we'll have to iterate on the serialization of the colormaps to account for different types

**Comment by lopezvoliver** [comment]
> This isn't quite working as expected for colormaps. I'm eager to incorporate this but we'll have to iterate on the serialization of the colormaps to account for different types

Can you share a couple of examples? I can give it a try

**Comment by banesullivan** [comment]
Sorry for my short comment, I'm unable to take a look immediately, but I was trying to do something like the following:

```py
from localtileserver import TileClient, get_leaflet_tile_layer, examples
from matplotlib.colors import ListedColormap, Colormap
from ipyleaflet import Map

tile_client = examples.get_bahamas(debug=True)

cmap1 = ListedColormap(['red','blue'],name='test_1')
cmap2 = ListedColormap(['blue','green'],name='test_2')
cmap3 = ListedColormap(['green','red'],name='test_3')

t = get_leaflet_tile_layer(tile_client, colormap=cmap1)
# t = get_leaflet_tile_layer(tile_client, colormap=[cmap2,cmap1,cmap3])

m = Map(center=tile_client.center(), zoom=tile_client.default_zoom)
m.add_layer(t)
m
```

**Comment by lopezvoliver** [comment]
@banesullivan can you explain a bit more what's supposed to happen with `colormap` in this line? is it going to be a concatenation of the three colormaps? 

```python
t = get_leaflet_tile_layer(tile_client, colormap=[cmap2,cmap1,cmap3])
```

What about the example with the single colormap? is that one working as expected?

**Comment by banesullivan** [comment]
>can you explain a bit more what's supposed to happen with colormap in this line? is it going to be a concatenation of the three colormaps?

Sorry for my delay! Let's ignore this actually. this was a supported feature when the underlying tile server used to be [large-image ](https://github.com/girder/large_image) where it had some rather unique capabilities for color mapping individual bands. I don't think we need to support that here.

**Comment by banesullivan** [comment]
I've gone ahead and fixed the remaining issues in order to use `ListedColormap` and `LinearSegmentedColormap` instances as well. I think this is good to merge at this point. @lopezvoliver or @giswqs, do you want to make sure that this works with leafmap before I merge/release?

**Review by banesullivan — APPROVED** [review]

**Comment by banesullivan** [comment]
I think its worth noting that in this current implementation, there is a limit to how big these colormaps can be as we embed them in the URL parameters. I recommend just creating named colormaps and registering them with matplotlib in your environment to get around this so that they can be referred to by name, ref: https://matplotlib.org/stable/users/explain/colors/colormap-manipulation.html#registering-a-colormap

**Comment by giswqs** [comment]
I tested it. Custom colormaps in the format of ListedColormap and list of colors (e.g., ['red', 'green']) work well with leafmap. 

Registering the custom colormap with matplotlib does not seem to work. Anyway, this is not a big issue. No worries if you don't have time look into it now. 

https://colab.research.google.com/drive/1JPgl3O-u1ufDEwb3f8fWxiXPqOQyPER7?usp=sharing

**Comment by banesullivan** [comment]
>Registering the custom colormap with matplotlib does not seem to work

Whoops, I thought this would. I'll try to make sure this gets fixed

**Comment by nve-sak** [comment]
FWIW, I added a failing test case here:  https://github.com/opengeos/leafmap/discussions/966. No crash or error, but the colors are not as expected.

**Pull request merged**
