### PR TITLE
Switch to rasterio

### PR DESCRIPTION
**Pull request by banesullivan**
With the addition of the new `rasterio` based source module in `large-image`, I have decided to go all in on `rasterio` here and drop GDAL use. Additionally, I have decided to limit the scope of this project to only geospatial images moving forward (since large-image has development underway for better non-geo visualization in Jupyter).

This is a start to a handful of changes that will ultimately make `localtileserver` easier to use and more performant.

With this switch to rasterio and some significant internal refactoring, this will warrant a major version bump -- `v1.0.0` is on its way

### CODE REVIEW

**Comment by banesullivan** [comment]
cc @giswqs, I think you'll be happy to see this! But this PR is completely changing the dependency stack and may impact your usage

**Comment by giswqs** [comment]
This is great. It will make the installation much easier. I will keep an eye on this and make changes downstream accordingly

**Comment by banesullivan** [comment]
Going ahead with a merge as I'd like to do some other internal refactoring. Release is not coming immediately as I need to do more testing and want feedback from @giswqs

**Comment by giswqs** [comment]
Sure. I can help with testing

**Pull request merged**
