### PR TITLE
Multiband support and MPL colormaps

### LINKED ISSUE #22: Support band selection for multi-spectral imagery
The `band` parameter of `get_leaflet_tile_layer()` is an integer type. I would suggest adding support for band selection when there are more than 3 bands, e.g., `band=[4, 3, 2]` 

Sample dataset: [landsat.tif](https://drive.google.com/file/d/1EV38RjNxdwEozjc9m0FcO3LFgAoAX1Uw/view?usp=sharing) (7 bands)

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

url = "/home/qiusheng/Downloads/landsat.tif"
# First, create a tile server from local raster file
tile_client = TileClient(url)

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```
image

In QGIS
image

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #22 

This all feels a bit hacky, but it works. @giswqs, would you please review/test.

Here is an example

```py
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
tile_client = TileClient('./landsat.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client, band=[4, 3, 2])

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```

Screen Shot 2021-12-05 at 1 12 18 PM 1

or like the screenshots in #22:

```py
# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client, band=[5, 4, 3])

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```

Screen Shot 2021-12-05 at 1 17 28 PM

-----

To do:
- [x] Update type hints and documentation 
- [x] Add example to README
- [ ] User test

### CODE REVIEW

**Comment by banesullivan** [comment]
Also, @giswqs, what Landsat data is thise? 7? 8? I'd like to use it for a demo and know which bands are what per something like: http://gsp.humboldt.edu/olm/Courses/GSP_216/lessons/composites.html

**Comment by banesullivan** [comment]
This example was added to the README:

```py
rom localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map, ScaleControl, FullScreenControl, SplitMapControl

# First, create a tile server from local raster file
tile_client = TileClient('landsat.tif')

# Create 2 tile layers from same raster viewing different bands
l = get_leaflet_tile_layer(tile_client, band=[7, 5, 4])
r = get_leaflet_tile_layer(tile_client, band=[5, 3, 2])

# Make the ipyleaflet map
m = Map(center=tile_client.center(), zoom=12)
control = SplitMapControl(left_layer=l, right_layer=r)
m.add_control(control)
m.add_control(ScaleControl(position='bottomleft'))
m.add_control(FullScreenControl())
m
```

ipyleaflet-multi-bands

**Comment by giswqs** [comment]
This is AWESOME! I can confirm that it works for both local raster datasets and remote pre-tiled COG. The sample dataset I provided is Landsat 7 image. 

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
# tile_client = TileClient('./landsat7.tif')
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'

tile_client = TileClient(url)

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client, band=[3, 2, 1])

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m

```

**Comment by giswqs** [comment]
By default, if `band` is not provided, the image looks like this. Maybe there is a nodata issue?

image

**Comment by giswqs** [comment]
Here is the dataset I used for the example above. 
https://drive.google.com/file/d/16ji8ze8gqSR1kJssf7vqdhR3d58ZBYT0/view?usp=sharing

**Comment by banesullivan** [comment]
I can reproduce that visual effect with the shared file on my end. I suspect there is an issue with the alpha channel on that particular image rather than a nodata issue or an issue with the tile serving

**Pull request merged**
